version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build_and_test:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run: gem install bundler
      - ruby/bundle-install
      - run: bundle exec rspec